apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: xlate-oc
    labels:
        app: gs-mgmt
        gs-mgmt: xlate-oc
spec:
    selector:
        matchLabels:
            app: xlate-oc
    template:
        metadata:
            labels:
                app: xlate-oc
        spec:
            containers:
            - name: xlate-oc
              image: MGMT_IMAGE_REPO/xlate-oc:IMAGE_TAG
              imagePullPolicy: IfNotPresent
              command: ['gsxlated-openconfig']
              args: ['--verbose', '$(OPERATIONAL_MODES_FILE)']
              env:
              - name: OPERATIONAL_MODES_FILE
                value: /current/operational-modes.json
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: current
                mountPath: /current
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 10
                periodSeconds: 5
                timeoutSeconds: 5
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: current
              hostPath:
                  path: /var/lib/goldstone/device/current
