apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: xlate-oc
    labels:
        app: gs-mgmt
        gs-mgmt: xlate-oc
spec:
    selector:
        matchLabels:
            app: xlate-oc
    template:
        metadata:
            labels:
                app: xlate-oc
        spec:
            containers:
            - name: xlate-oc
              image: MGMT_IMAGE_REPO/xlate-oc:IMAGE_TAG
              imagePullPolicy: IfNotPresent
              command: ['gsxlated-openconfig', '-v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
