apiVersion: v1
kind: Service
metadata:
  name: ocnos-cluster-ip
  namespace: default
spec:
  selector:
    name: ocnos
  ports:
  - name: port
    protocol: TCP
    port: 30830
    targetPort: 830

---

apiVersion: v1
kind: Pod
metadata:
  name: ocnos
  namespace: default
  labels:
    name: ocnos
spec:
  containers:
  - name: ocnos
    image: ocnos:latest
    imagePullPolicy: Never
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
    volumeMounts:
    - mountPath: /usr/lib/modules/4.19.91-opennetworklinux
      name: usr-modules
    - mountPath: /lib/modules/4.19.91-opennetworklinux
      name: lib-modules
    - mountPath: /cfg
      name: cfg 
    - mountPath: /sys/devices
      name: sys-devices
      readOnly: false
    ports:
      - containerPort: 80
  volumes:
  - name: usr-modules
    hostPath:
      path: /usr/lib/modules/4.19.91-opennetworklinux
  - name: lib-modules
    hostPath:
      path: /lib/modules/4.19.91-opennetworklinux
  - name: cfg
    hostPath:
      path: /var/lib/ocnos/cfg
  - name: sys-devices
    hostPath:
      path: /sys/devices
