apiVersion: v1
kind: Pod
metadata:
    name: usonic-cli
spec:
    containers:
    - name: cli
      image: ghcr.io/oopt-goldstone/usonic-cli:201904
      imagePullPolicy: IfNotPresent
      command: ['bash', '-c', 'trap : TERM INT; sleep infinity & wait']
      env:
      - name: DEFAULT_DB_HOST
        value: "redis.default.svc.cluster.local"
      volumeMounts:
      - name: sonic-db-config
        mountPath: /var/run/redis/sonic-db/
      - name: sonic-version
        mountPath: /etc/sonic/
      - name: usonic-config
        mountPath: /etc/usonic/
    volumes:
    - name: sonic-db-config
      configMap:
          name: sonic-db-config
    - name: sonic-version
      configMap:
          name: usonic-config
          items:
          - key: sonic_version.yml
            path: sonic_version.yml
    - name: usonic-config
      configMap:
          name: usonic-config
    terminationGracePeriodSeconds: 0
