apiVersion: v1
kind: ConfigMap
metadata:
  name: start-script
data:
  start.sh: | 
    #!/bin/sh
    set -eux

    REDIS_HOST='-h redis.default.svc.cluster.local'
    # REDIS_HOST='-h 127.0.0.1'

    redis-cli ${REDIS_HOST} flushall

    for daemon in syncd:syncd intfmgrd:intfmgrd orchagent:orchagent portsyncd:portsyncd neighsyncd:neighsyncd vlanmgrd:vlanmgrd;
    do
        redis-cli -n 3 ${REDIS_HOST} hset $daemon LOGOUTPUT STDERR;
    done
