apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: north-notif
spec:
    template:
        spec:
            containers:
            - name: notif
              image: MGMT_IMAGE_REPO/north-notif:IMAGE_TAG
