apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-sonic
spec:
    template:
        spec:
            containers:
            - name: sonic
              image: MGMT_IMAGE_REPO/south-sonic:IMAGE_TAG
