apiVersion: apps/v1
kind: Deployment
metadata:
    name: tai-gearbox
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tai-gearbox
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: tai-gearbox
        spec:
            containers:
            - name: taish-server
              image: tai-arm64:latest
              imagePullPolicy: IfNotPresent
              command: ['taish_server']
              args: ['-v']
              env:
              - name: LD_LIBRARY_PATH
                value: "/var/lib/tai"
              volumeMounts:
              - name: host-libtai
                mountPath: /var/lib/tai
              - name: tai-config
                mountPath: /etc/tai
              securityContext:
                privileged: true
            volumes:
            - name: host-libtai
              hostPath:
                path: /var/lib/tai-gearbox/
            - name: tai-config
              hostPath:
                path: /var/lib/goldstone/device/current/tai-gearbox
