apiVersion: v1
kind: Service
metadata:
    name: north-netconf
    labels:
        gs-mgmt: north-netconf
spec:
    type: LoadBalancer
    selector:
        app: north-netconf
    ports:
    - protocol: TCP
      port: 830
      targetPort: 830
      name: netconf

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: north-netconf
    labels:
        app: gs-mgmt
        gs-mgmt: north-netconf
spec:
    selector:
        matchLabels:
            app: north-netconf
    template:
        metadata:
            labels:
                app: north-netconf
        spec:
            containers:
            - name: netopeer2
              image: MGMT_IMAGE_REPO/north-netconf:IMAGE_TAG
              imagePullPolicy: IfNotPresent
              command: ['netopeer2-server']
              args: ['-d', '-v', '2', '-t', '60']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: home
                mountPath: /home
                readOnly: true
              - name: passwd
                mountPath: /etc/passwd
                readOnly: true
              - name: shadow
                mountPath: /etc/shadow
                readOnly: true
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: home
              hostPath:
                  path: /home
            - name: passwd
              hostPath:
                  path: /etc/passwd
            - name: shadow
              hostPath:
                  path: /etc/shadow
