apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-dpll
spec:
    template:
        spec:
            containers:
            - name: dpll
              image: MGMT_IMAGE_REPO/south-dpll:IMAGE_TAG
